package ir.metra.app.core.pdf

/**
 * The report *document model*.
 *
 * Deliberately free of Android types: business code describes a report as data
 * and [PdfReportEngine] is the only place that knows how to draw it. That keeps
 * report content testable on the JVM and lets the same model feed CSV or JSON
 * export later.
 */

/** Horizontal alignment inside a cell or line. */
enum class PdfAlign { START, CENTER, END }

/** Text weight. */
enum class PdfWeight { REGULAR, MEDIUM, BOLD }

/** A block of content in a report. */
sealed interface PdfBlock {

    /** A paragraph. [rtl] text is aligned to the right edge by default. */
    data class Paragraph(
        val text: String,
        val style: PdfTextStyle = PdfTextStyle.Body,
        val align: PdfAlign = PdfAlign.START,
        val spaceBeforePt: Float = 0f,
        val spaceAfterPt: Float = 4f,
        val rtl: Boolean = true,
    ) : PdfBlock

    /** A single rule used to separate sections. */
    data class Divider(val spaceBeforePt: Float = 6f, val spaceAfterPt: Float = 6f) : PdfBlock

    /** Blank vertical space. */
    data class Spacer(val heightPt: Float) : PdfBlock

    /** A table with a repeated header row. */
    data class Table(
        val columns: List<PdfColumn>,
        val header: List<String>,
        val rows: List<List<String>>,
        val aligns: List<PdfAlign>,
        val caption: String? = null,
        val rtl: Boolean = true,
    ) : PdfBlock

    /** A two-column label/value list — the summary cards of a report. */
    data class KeyValueList(
        val entries: List<Pair<String, String>>,
        val labelWeight: PdfWeight = PdfWeight.MEDIUM,
        val rtl: Boolean = true,
        /** Rows whose value should be emphasised (totals, net amount). */
        val emphasisedLabels: Set<String> = emptySet(),
    ) : PdfBlock
}

/** One table column. */
data class PdfColumn(
    val title: String,
    /** Relative width; the engine scales the set to fit the content width. */
    val weight: Float = 1f,
    val minWidthPt: Float = 0f,
)

/** Text styles used across the document. */
enum class PdfTextStyle {
    Title,
    Subtitle,
    SectionHeader,
    Body,
    Small,
    TableHeader,
    TableCell,
}

/** Everything needed to render one report. */
data class PdfDocumentSpec(
    val title: String,
    val subtitle: String? = null,
    val headerLines: List<String> = emptyList(),
    val blocks: List<PdfBlock>,
    val footerText: String = "Generated by Metra",
    val pageNumbers: Boolean = true,
    val documentLanguageTag: String = "fa",
)
